# Change these first
owner: abaertsoen # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: BriefPoint
    url: https://www.briefpoint.fr
  - name: Dreamension
    url: https://dreamension.fr
  - name: Infochat
    url: https://www.infochat.fr
  - name: JV360
    url: https://jv360.fr
  - name: Musga
    url: https://musga.fr
  - name: PetitGeste
    url: https://petitgeste.fr
  - name: Shop Aishy
    url: https://aishy.fr
  - name: Shop Yuudoku
    url: https://yuudoku.jv360.fr

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.dreamension.fr
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dreamension Ecosystem Statuses
  introTitle: "**DES** monitores the front services of all the Dreamension's affiliated ecosystem."
  introMessage: This page uses **real-time** data from our services.
  navbar:
    - title: Status
      href: /
    - title: Dreamension
      href: https://dreamension.fr

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
